on:
  push:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grüezi Welt
        run: |
          echo "Grüezi Welt"
